# Generated by Django 4.1.4 on 2024-02-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.IntegerField()),
                ('gender', models.CharField(max_length=8)),
                ('age', models.IntegerField()),
                ('hypertension', models.IntegerField()),
                ('heart_disease', models.IntegerField()),
                ('ever_married', models.CharField(max_length=32)),
                ('work_type', models.CharField(max_length=32)),
                ('residence_type', models.CharField(max_length=32)),
                ('avg_glucose_level', models.FloatField()),
                ('bmi', models.FloatField()),
                ('smoking_status', models.CharField(max_length=32)),
                ('stroke', models.IntegerField()),
            ],
        ),
    ]
